{{- if .Values.githubPat }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-{{ .Values.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.vaultStorage }}
    kind: SecretStore
  target:
    name: {{ .Values.secretName }}
  data:
    - secretKey: {{ .Values.secretKey }}
      remoteRef:
        key: {{ .Values.vault.github.key }}
        property: {{ .Values.vault.github.property }}

{{- end }}
---
{{- if .Values.psrSecrets.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-{{ .Values.psrSecrets.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.vaultStorage }}
    kind: SecretStore
  target:
    name: {{ .Values.psrSecrets.secretName }}
  data:
    - secretKey: {{ .Values.psrSecrets.secretKey }}.yml
      remoteRef:
        key: {{ .Values.vault.psr.key }}
        property: {{ .Values.vault.psr.property }}

  {{- end }}

