{{- if .Values.githubPat }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-{{ .Values.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.vaultStorage }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
  data:
    - secretKey: {{ .Values.secretKey }}
      remoteRef:
        key: {{ .Values.vault.github.key }}
        property: {{ .Values.vault.github.property }}

{{- end }}
---
{{- if .Values.psrSecrets.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-{{ .Values.psrSecrets.secretName }}
  labels:
    app.kubernetes.io/component: deployment
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.vaultStorage }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.psrSecrets.secretName }}
    template:
      data:
        {{ .Values.psrSecrets.secretName }}.yml: |
          step-runner-config:
            global-defaults:
              container-registries:
                {{`{{ .registry0Host }}`}}:
                  username: {{`{{ .registry0User }}`}}
                  password: {{`{{ .registry0Password }}`}}
                {{`{{ .registry1Host }}`}}:
                  username: {{`{{ .registry1User }}`}}
                  password: {{`{{ .registry1Password }}`}}

  data:
    - secretKey: registry0Host
      remoteRef:
        key: {{ .Values.vault.registry0.host.key }}
        property: {{ .Values.vault.registry0.host.property }}
    - secretKey: registry0User
      remoteRef:
        key: {{ .Values.vault.registry0.user.key }}
        property: {{ .Values.vault.registry0.user.property }}
    - secretKey: registry0Password
      remoteRef:
        key: {{ .Values.vault.registry0.password.key }}
        property: {{ .Values.vault.registry0.password.property }}
    - secretKey: registry1Host
      remoteRef:
        key: {{ .Values.vault.registry1.host.key }}
        property: {{ .Values.vault.registry1.host.property }}
    - secretKey: registry1User
      remoteRef:
        key: {{ .Values.vault.registry1.user.key }}
        property: {{ .Values.vault.registry1.user.property }}
    - secretKey: registry1Password
      remoteRef:
        key: {{ .Values.vault.registry1.password.key }}
        property: {{ .Values.vault.registry1.password.property }}

{{- end }}
---
apiVersion: v1
data:
  token: cm9vdA==
kind: Secret
metadata:
  name: vault-secret
  namespace: github-runners
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: github-runners
spec:
  provider:
    vault:
      server: "http://vault-internal.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-secret"
          key: "token"
---